import PastaBench.leetcode.MaximumCandiesAllocatedToKChildren.Generated
namespace PastaBench.leetcode.MaximumCandiesAllocatedToKChildren
-- TODO.
end PastaBench.leetcode.MaximumCandiesAllocatedToKChildren
