import PastaBench.leetcode.MinimumOperationsToMakeTheIntegerZero.Generated
namespace PastaBench.leetcode.MinimumOperationsToMakeTheIntegerZero
-- TODO.
end PastaBench.leetcode.MinimumOperationsToMakeTheIntegerZero
