import PastaBench.leetcode.NumberOfTimesBinaryStringIsPrefixAligned.Generated
namespace PastaBench.leetcode.NumberOfTimesBinaryStringIsPrefixAligned
-- TODO.
end PastaBench.leetcode.NumberOfTimesBinaryStringIsPrefixAligned
