import PastaBench.leetcode.NumberOfDistinctSubstringsInAString.Generated
namespace PastaBench.leetcode.NumberOfDistinctSubstringsInAString
-- TODO.
end PastaBench.leetcode.NumberOfDistinctSubstringsInAString
