import PastaBench.leetcode.KthSmallestNumberInMultiplicationTable.Generated
namespace PastaBench.leetcode.KthSmallestNumberInMultiplicationTable
-- TODO.
end PastaBench.leetcode.KthSmallestNumberInMultiplicationTable
