import PastaBench.leetcode.CountSubstringsStartingAndEndingWithGivenCharacter.Generated
namespace PastaBench.leetcode.CountSubstringsStartingAndEndingWithGivenCharacter
-- TODO: state and prove.
end PastaBench.leetcode.CountSubstringsStartingAndEndingWithGivenCharacter
