import PastaBench.leetcode.FindMinimumInRotatedSortedArrayIi.Generated
namespace PastaBench.leetcode.FindMinimumInRotatedSortedArrayIi
-- TODO.
end PastaBench.leetcode.FindMinimumInRotatedSortedArrayIi
