import PastaBench.leetcode.FindTheLongestSemiRepetitiveSubstring.Generated
namespace PastaBench.leetcode.FindTheLongestSemiRepetitiveSubstring
-- TODO.
end PastaBench.leetcode.FindTheLongestSemiRepetitiveSubstring
