import PastaBench.leetcode.MinimumOperationsToMakeArrayEqual.Generated
namespace PastaBench.leetcode.MinimumOperationsToMakeArrayEqual
-- TODO.
end PastaBench.leetcode.MinimumOperationsToMakeArrayEqual
