import PastaBench.leetcode.SubstringsThatBeginAndEndWithTheSameLetter.Generated
namespace PastaBench.leetcode.SubstringsThatBeginAndEndWithTheSameLetter
-- TODO.
end PastaBench.leetcode.SubstringsThatBeginAndEndWithTheSameLetter
