import PastaBench.leetcode.CountEqualAndDivisiblePairsInAnArray.Generated
namespace PastaBench.leetcode.CountEqualAndDivisiblePairsInAnArray
-- TODO.
end PastaBench.leetcode.CountEqualAndDivisiblePairsInAnArray
